package pojos;
// Generated Feb 23, 2018 12:49:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DriverHasVehicledetails generated by hbm2java
 */
public class DriverHasVehicledetails  implements java.io.Serializable {


     private Integer driverHasVehicledetailsid;
     private Driver driver;
     private Vehicledetails vehicledetails;
     private Set<Tripdetails> tripdetailses = new HashSet<Tripdetails>(0);

    public DriverHasVehicledetails() {
    }

	
    public DriverHasVehicledetails(Driver driver, Vehicledetails vehicledetails) {
        this.driver = driver;
        this.vehicledetails = vehicledetails;
    }
    public DriverHasVehicledetails(Driver driver, Vehicledetails vehicledetails, Set<Tripdetails> tripdetailses) {
       this.driver = driver;
       this.vehicledetails = vehicledetails;
       this.tripdetailses = tripdetailses;
    }
   
    public Integer getDriverHasVehicledetailsid() {
        return this.driverHasVehicledetailsid;
    }
    
    public void setDriverHasVehicledetailsid(Integer driverHasVehicledetailsid) {
        this.driverHasVehicledetailsid = driverHasVehicledetailsid;
    }
    public Driver getDriver() {
        return this.driver;
    }
    
    public void setDriver(Driver driver) {
        this.driver = driver;
    }
    public Vehicledetails getVehicledetails() {
        return this.vehicledetails;
    }
    
    public void setVehicledetails(Vehicledetails vehicledetails) {
        this.vehicledetails = vehicledetails;
    }
    public Set<Tripdetails> getTripdetailses() {
        return this.tripdetailses;
    }
    
    public void setTripdetailses(Set<Tripdetails> tripdetailses) {
        this.tripdetailses = tripdetailses;
    }




}


