package pojos;
// Generated Feb 23, 2018 12:49:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private Integer iddriver;
     private Bloodgroup bloodgroup;
     private String nic;
     private String fname;
     private String lname;
     private String licenseno;
     private String contactno;
     private String emergencyno;
     private String password;
     private Set<DriverHasVehicledetails> driverHasVehicledetailses = new HashSet<DriverHasVehicledetails>(0);

    public Driver() {
    }

	
    public Driver(Bloodgroup bloodgroup) {
        this.bloodgroup = bloodgroup;
    }
    public Driver(Bloodgroup bloodgroup, String nic, String fname, String lname, String licenseno, String contactno, String emergencyno, String password, Set<DriverHasVehicledetails> driverHasVehicledetailses) {
       this.bloodgroup = bloodgroup;
       this.nic = nic;
       this.fname = fname;
       this.lname = lname;
       this.licenseno = licenseno;
       this.contactno = contactno;
       this.emergencyno = emergencyno;
       this.password = password;
       this.driverHasVehicledetailses = driverHasVehicledetailses;
    }
   
    public Integer getIddriver() {
        return this.iddriver;
    }
    
    public void setIddriver(Integer iddriver) {
        this.iddriver = iddriver;
    }
    public Bloodgroup getBloodgroup() {
        return this.bloodgroup;
    }
    
    public void setBloodgroup(Bloodgroup bloodgroup) {
        this.bloodgroup = bloodgroup;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getLicenseno() {
        return this.licenseno;
    }
    
    public void setLicenseno(String licenseno) {
        this.licenseno = licenseno;
    }
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    public String getEmergencyno() {
        return this.emergencyno;
    }
    
    public void setEmergencyno(String emergencyno) {
        this.emergencyno = emergencyno;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<DriverHasVehicledetails> getDriverHasVehicledetailses() {
        return this.driverHasVehicledetailses;
    }
    
    public void setDriverHasVehicledetailses(Set<DriverHasVehicledetails> driverHasVehicledetailses) {
        this.driverHasVehicledetailses = driverHasVehicledetailses;
    }




}


