package pojos;
// Generated Feb 23, 2018 12:49:42 PM by Hibernate Tools 3.6.0



/**
 * Feetype generated by hbm2java
 */
public class Feetype  implements java.io.Serializable {


     private Integer idfeetype;
     private Vehicle vehicle;
     private String type;
     private Double basicfee;
     private Double feefor1km;
     private Integer defaultwaitingtimeMin;
     private Double feeforwaitingtime;
     private Double nightbasicfee;
     private Double nightfeeforkm;
     private Double nightfeeforwaitingMin;

    public Feetype() {
    }

	
    public Feetype(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Feetype(Vehicle vehicle, String type, Double basicfee, Double feefor1km, Integer defaultwaitingtimeMin, Double feeforwaitingtime, Double nightbasicfee, Double nightfeeforkm, Double nightfeeforwaitingMin) {
       this.vehicle = vehicle;
       this.type = type;
       this.basicfee = basicfee;
       this.feefor1km = feefor1km;
       this.defaultwaitingtimeMin = defaultwaitingtimeMin;
       this.feeforwaitingtime = feeforwaitingtime;
       this.nightbasicfee = nightbasicfee;
       this.nightfeeforkm = nightfeeforkm;
       this.nightfeeforwaitingMin = nightfeeforwaitingMin;
    }
   
    public Integer getIdfeetype() {
        return this.idfeetype;
    }
    
    public void setIdfeetype(Integer idfeetype) {
        this.idfeetype = idfeetype;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Double getBasicfee() {
        return this.basicfee;
    }
    
    public void setBasicfee(Double basicfee) {
        this.basicfee = basicfee;
    }
    public Double getFeefor1km() {
        return this.feefor1km;
    }
    
    public void setFeefor1km(Double feefor1km) {
        this.feefor1km = feefor1km;
    }
    public Integer getDefaultwaitingtimeMin() {
        return this.defaultwaitingtimeMin;
    }
    
    public void setDefaultwaitingtimeMin(Integer defaultwaitingtimeMin) {
        this.defaultwaitingtimeMin = defaultwaitingtimeMin;
    }
    public Double getFeeforwaitingtime() {
        return this.feeforwaitingtime;
    }
    
    public void setFeeforwaitingtime(Double feeforwaitingtime) {
        this.feeforwaitingtime = feeforwaitingtime;
    }
    public Double getNightbasicfee() {
        return this.nightbasicfee;
    }
    
    public void setNightbasicfee(Double nightbasicfee) {
        this.nightbasicfee = nightbasicfee;
    }
    public Double getNightfeeforkm() {
        return this.nightfeeforkm;
    }
    
    public void setNightfeeforkm(Double nightfeeforkm) {
        this.nightfeeforkm = nightfeeforkm;
    }
    public Double getNightfeeforwaitingMin() {
        return this.nightfeeforwaitingMin;
    }
    
    public void setNightfeeforwaitingMin(Double nightfeeforwaitingMin) {
        this.nightfeeforwaitingMin = nightfeeforwaitingMin;
    }




}


