package pojos;
// Generated Feb 23, 2018 12:49:42 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicledetails generated by hbm2java
 */
public class Vehicledetails  implements java.io.Serializable {


     private Integer idvehicledetails;
     private Vehicle vehicle;
     private String vehicleregno;
     private Set<DriverHasVehicledetails> driverHasVehicledetailses = new HashSet<DriverHasVehicledetails>(0);

    public Vehicledetails() {
    }

	
    public Vehicledetails(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Vehicledetails(Vehicle vehicle, String vehicleregno, Set<DriverHasVehicledetails> driverHasVehicledetailses) {
       this.vehicle = vehicle;
       this.vehicleregno = vehicleregno;
       this.driverHasVehicledetailses = driverHasVehicledetailses;
    }
   
    public Integer getIdvehicledetails() {
        return this.idvehicledetails;
    }
    
    public void setIdvehicledetails(Integer idvehicledetails) {
        this.idvehicledetails = idvehicledetails;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public String getVehicleregno() {
        return this.vehicleregno;
    }
    
    public void setVehicleregno(String vehicleregno) {
        this.vehicleregno = vehicleregno;
    }
    public Set<DriverHasVehicledetails> getDriverHasVehicledetailses() {
        return this.driverHasVehicledetailses;
    }
    
    public void setDriverHasVehicledetailses(Set<DriverHasVehicledetails> driverHasVehicledetailses) {
        this.driverHasVehicledetailses = driverHasVehicledetailses;
    }




}


